import{i as f,S as E,a as $}from"./assets/vendor-eeed083b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const M="https://pixabay.com/api/",m="41911500-2109ce3c8bb16633259977e96",c=document.querySelector(".gallery"),p=document.querySelector(".search-form");document.querySelector(".search-input");document.querySelector(".start-btn");const u=document.querySelector(".loader"),n=document.querySelector(".load-btn");document.querySelector("loader-load");const d="is-hidden";let y="",i=1,h=0;u.style.display="none";p.addEventListener("submit",P);function P(o){o.preventDefault(),u.style.display="block",y=o.target.elements.query.value,g(y).then(r=>{u.style.display="none",r.hits.length||f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),c.innerHTML="",i=1;try{c.innerHTML=L(r.hits),new E(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),q(),r.totalHits>0?(n.classList.remove(d),n.addEventListener("click",b)):n.classList.add(d)}catch{S()}finally{p.reset()}})}function g(o,r=1){return $.get(`${M}?key=${m}&q=${o}`,{params:{apiKey:m,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:5,page:r}}).then(({data:s})=>s)}function L(o){return o.map(({webformatURL:r,largeImageURL:s,tags:l,likes:e,views:t,comments:a,downloads:v})=>`
  <li class="gallery-item">
  <a class="gallery-link" href="${s}">
    <img
      class="gallery-image"
      src="${r}"
      alt="${l}"
    />
    <p class= "gallery-descr">• Likes: ${e} • Views: ${t} • Comments: ${a} •</span> Downloads:${v}</p>
  </a>
</li>
  `).join("")}async function b(){i+=1,n.disabled=!0;try{const{hits:o,total:r}=await g(y,i);h=Math.ceil(r/40),c.insertAdjacentHTML("beforeend",L(o)),q()}catch{S()}finally{n.disabled=!1,i===h&&(n.classList.add(d),n.removeEventListener("click",b),f.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}))}}function S(o){f.error({title:"Error",message:"OOps... Plese try again"})}function q(){window.scrollBy({top:700,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
